# You can easily switch between different databases by changing the value of COMPOSE_PROFILES in the .env file.
services:
  web:
    build: { context: "." }
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
    depends_on:
      - ${COMPOSE_PROFILES-postgres}
    environment:
      DATABASE_URL: ${COMPOSE_PROFILES-postgres}://root:secret@${COMPOSE_PROFILES:-postgres}/sqlpage
  postgres:
    profiles: ["postgres"]
    ports: ["5432:5432"]
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: sqlpage
      POSTGRES_PASSWORD: secret
  mysql:
    profiles: ["mysql"]
    ports: ["3306:3306"]
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: sqlpage
  mssql:
    profiles: ["mssql"]
    ports: ["1433:1433"]
    build: { context: "mssql" }