name: docker

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/release.yml'
      - '.github/workflows/official-site.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: lovasoa
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: lovasoa/sqlpage:latest,lovasoa/sqlpage:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
