name: Lint, format, and test

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/release.yml'
      - '.github/workflows/official-site.yml'
  pull_request:
    branches:
      - 'main'

env:
  CARGO_TERM_COLOR: always

jobs:
  compile_and_lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up cargo cache
      uses: Swatinem/rust-cache@dd05243424bd5c0e585e4b55eb2d7615cdd32f1f
    - run: cargo fmt --all -- --check
    - run: cargo clippy
    - run: cargo test --all-features
    - run: cargo test

  test:
    needs: compile_and_lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database: ['postgres', 'mysql', 'mssql']
    steps:
    - uses: actions/checkout@v3
    - name: Set up cargo cache
      uses: Swatinem/rust-cache@dd05243424bd5c0e585e4b55eb2d7615cdd32f1f
    - name: Start database container
      run: docker-compose up -d ${{ matrix.database }}
    - name: Run tests against ${{ matrix.database }}
      run: cargo test
      env:
        DATABASE_URL: ${{ matrix.database }}://root:Password123!@127.0.0.1/sqlpage

  windows_test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up cargo cache
      uses: Swatinem/rust-cache@dd05243424bd5c0e585e4b55eb2d7615cdd32f1f
    - run: cargo test
